version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es02,es01,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es04
    environment:
      - node.name=es04
      - discovery.seed_hosts=es02,es03,es01
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 80:5601
    networks:
      - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    environment:
      SERVER_NAME: logstash
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5044:5044
    networks:
      - esnet
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
networks:
  esnet: